version: "3.9"
services:
  cbc-mcp:
    platform: linux/arm64
    build: .
    image: cbc-mcp:latest
    container_name: cbc-mcp
    user: "10001:10001"
    working_dir: /app
    environment:
      - CACHE_DIR=/app/.cache
    volumes:
      - type: volume
        source: cbc_mcp_cache
        target: /app/.cache
        consistency: delegated
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "test", "-w", "/app/.cache"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

volumes:
  cbc_mcp_cache: {}
